name: Update Sidebar (with PAT)

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '_sidebar.md'
      - '.github/workflows/update-sidebar.yml'
      - '.github/workflows/update-sidebar-with-token.yml'
  workflow_dispatch:

jobs:
  update-sidebar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Generate sidebar
      run: |
        python3 .github/scripts/generate-sidebar.py

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add _sidebar.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update sidebar"
          git push
        fi 